project:
  type: book
  output-dir: docs
  
book:
  title: "Microeconometrics"
  author: "Neil Lloyd"
  date: "2024-01-02"
  chapters:
    - index.qmd
    - intro.qmd
    - cef.qmd
    - part: "Parametric Models"
      chapters:
        - regression.qmd 
        - instruments.qmd
        - panel.qmd
    - causality.qmd
    - part: "Controlled Experiments"
      chapters:
        - classical.qmd
        - stratified.qmd
        - noncompliance.qmd
    - part: "Observational Studies" 
      chapters:
        - regular.qmd
        - commonsupport.qmd
    - part: "Natural Experiments"
      chapters:
        - paralleltrends.qmd
        - staggereddid.qmd
        - synthetic.qmd
        - discontinuities.qmd
    - discussion.qmd
  appendices:
    - references.qmd
    - superPopVar.qmd
    - DAG.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

