project:
  type: book
  output-dir: docs
  
book:
  title: "Microeconometrics"
  author: "Neil Lloyd"
  date: "2024-01-02"
  chapters:
    - index.qmd
    - intro.qmd
    - cef.qmd
    - regression.qmd 
    - part: "IV"
      chapters:
        - instruments.qmd
        - panel.qmd
        - causality.qmd
    - part: "Experimental Design"
      chapters:
        - regular.qmd
        - irregular.qmd
        - unconfoundedness.qmd
    - observational.qmd
    - paralleltrends.qmd
    - discontinuities.qmd
    - discussion.qmd
    - references.qmd
    

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

